/**
 * @ts-check
 *
 * GeneralUpdate documentation sidebar.
 *
 * Pages are grouped by role:
 *   1. Quick Start          — Beginner cookbook & Tools reference
 *   2. Components           — non-firmware component reference (Core, Bowl,
 *                              Differential, Drivelution, Extension)
 *   3. Help                 — operational / platform-specific guides
 *   4. Release Log          — changelog and roadmap
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // ── 1. Quick Start ──────────────────────────────────────────────
    {
      type: 'category',
      label: 'Quick Start',
      collapsed: false,
      items: [
        'quickstart/Beginner cookbook',
        'quickstart/GeneralUpdate.PacketTool',
      ],
    },

    // ── 2. Components ───────────────────────────────────────────────
    {
      type: 'category',
      label: 'Components',
      collapsed: false,
      items: [
        'doc/Component Introduction',
        'doc/GeneralUpdate.Core',
        'doc/GeneralUpdate.Bowl',
        'doc/GeneralUpdate.Differential',
        'doc/GeneralUpdate.Drivelution',
        'doc/GeneralUpdate.Extension',
        'doc/Android auto-update',
      ],
    },

    // ── 3. Help ─────────────────────────────────────────────────────
    {
      type: 'category',
      label: '帮助',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'guide' },
      ],
    },

    // ── 4. Release Log ──────────────────────────────────────────────
    {
      type: 'category',
      label: 'Release Log',
      collapsed: true,
      items: [
        'releaselog/GeneralUpdateReleaselog',
      ],
    },
  ],
};

export default sidebars;
