/**
 * @ts-check
 *
 * GeneralUpdate documentation sidebar.
 *
 * Pages are grouped by role:
 *   1. Quick Start & Cookbooks    — first-time user flow and advanced production guides
 *   2. Components                 — non-firmware component reference (Core, Bowl,
 *                                   Differential, Drivelution, Extension)
 *   3. Tools                      — GeneralUpdate.Tools usage and artifact reference
 *   4. Infrastructure             — server-side services (Spacestation, Hub, ClientCore)
 *   5. OSS Update Mode            — OSS-based update flows (.NET & MAUI)
 *   6. Utilities                  — shared helpers (GeneralTracer)
 *   7. Guides                     — operational / platform-specific guides
 *   8. Release Log                — changelog and roadmap
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    // ── 1. Quick Start & Cookbooks ──────────────────────────────────
    {
      type: 'category',
      label: 'Quick Start',
      collapsed: false,
      items: [
        'quickstart/Quik start',
        'quickstart/Sample UI',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Cookbook',
      collapsed: true,
      items: [
        'quickstart/Advanced cookbook',
      ],
    },

    // ── 2. Components (non-firmware) ────────────────────────────────
    {
      type: 'category',
      label: 'Components',
      collapsed: false,
      items: [
        'doc/Component Introduction',
        'doc/GeneralUpdate.Core',
        'doc/GeneralUpdate.Bowl',
        'doc/GeneralUpdate.Differential',
        'doc/GeneralUpdate.Drivelution',
        'doc/GeneralUpdate.Extension',
      ],
    },

    // ── 3. GeneralUpdate.Tools ──────────────────────────────────────
    {
      type: 'category',
      label: 'Tools',
      collapsed: true,
      items: [
        'doc/GeneralUpdate.PacketTool',
      ],
    },

    // ── 4. Infrastructure ───────────────────────────────────────────
    {
      type: 'category',
      label: 'Infrastructure',
      collapsed: true,
      items: [
        'doc/GeneralSpacestation',
        'doc/UpgradeHub',
        'doc/GeneralUpdate.ClientCore',
      ],
    },

    // ── 5. OSS Update Mode ──────────────────────────────────────────
    {
      type: 'category',
      label: 'OSS Update Mode',
      collapsed: true,
      items: [
        'doc/GeneralClient.OSS',
        'doc/GeneralUpdate.Maui.OSS',
      ],
    },

    // ── 6. Utilities ────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Utilities',
      collapsed: true,
      items: [
        'doc/GeneralTracer',
      ],
    },

    // ── 7. Guides ───────────────────────────────────────────────────
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'guide' },
      ],
    },

    // ── 8. Release Log ──────────────────────────────────────────────
    {
      type: 'category',
      label: 'Release Log',
      collapsed: true,
      items: [
        'releaselog/GeneralUpdateReleaselog',
      ],
    },
  ],
};

export default sidebars;
