# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies ServerSample.sln
      run: dotnet restore ./src/Server/ServerSample.sln

    - name: Restore dependencies ClientSample.sln
      run: dotnet restore ./src/Client/ClientSample.sln

    - name: Restore dependencies UpgradeSample.sln
      run: dotnet restore ./src/Upgrade/UpgradeSample.sln
