name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore & Build ServerSample
      run: dotnet build ./src/Server/ServerSample.sln

    - name: Restore & Build Hub (NuGet mode)
      run: dotnet build ./src/Hub/Hub.csproj -p:UseNuGet=true
