<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Irihi.Mafia"/>
        <PackageReference Include="Irihi.Mafia.Themes.TDesign"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GeneralUpdate.Samples.Shared\GeneralUpdate.Samples.Shared.csproj" />
    </ItemGroup>
</Project>
